[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"
base = "dark"

[browser]
gatherUsageStats = false

[global]
developmentMode = false
